# Generated by Django 4.2.7 on 2023-11-01 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='nickname',
            field=models.CharField(default='anonim', max_length=15),
        ),
        migrations.AddField(
            model_name='question',
            name='nickname',
            field=models.CharField(default='anonim', max_length=15),
        ),
    ]
