# Generated by Django 4.2.7 on 2023-11-02 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_choice_nickname_question_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='nickname',
        ),
    ]
